protocol + markets
davekaj/lending-subgraph-standard pull request #6
Opened 2022-03-27 05:20 UTC by nmimran99

2022-03-27 05:21 UTC, nmimran99 commented
https://thegraph.com/hosted-service/subgraph/nmimran99/aave-v3?selected=playground

2022-03-28 02:58 UTC, davekaj requested changes
Nice PR, easy to read and good size. 

2 small comments before merging.

also going forwards let's start adding PR descriptions. for now, just a sentence or two is fine. We have no coding patterns to follow as a team yet, but soon we will create them :) 

You can also assign me to the PR whenever you have them ready!

2022-03-28 02:58 UTC, davekaj commented on subgraphs/aave-v3/subgraph.yaml
> +description: Compound is an open-source protocol for algorithmic, efficient Money Markets on the Ethereum blockchain.
copy paste error - this is still referencing compound, but its for aave

2022-03-28 02:58 UTC, davekaj commented on schema.graphql
> +}
did you intend to keep this in the schema? Or were you testing it to see the Pool Configurator and Pool Proxy in the query results?

2022-03-28 20:16 UTC, nmimran99 commented
Events:
Borrow, Withdraw, Repay, Liquidate, Deposit

Added tracking for reserve data updated:
ReserveDataUpdated

2022-03-29 14:35 UTC, davekaj requested changes
please fix requests

2022-03-29 14:35 UTC, davekaj commented on schema.graphql
> +  variableBorrowIndex: BigInt
A lot of these are AAVE specific fields. Which may have to be removed becasue they are not general enough. 

for now im okay keeping all of them. but they might need to be removed or renamed (for example `liquidityIndex` is poorly named by aave, it does not communicate what the variable represents)

2022-03-29 14:35 UTC, davekaj commented on schema.graphql
> +  referralCode: Int
I think referral code is unlikely to be used by us for a very long time, if ever. I think we can remove it

2022-03-29 14:35 UTC, davekaj commented on subgraphs/aave-v2/config/ethereum.json
> -    "network": "ethereum",
please add this back - we are going to need this type of configuration to index AAVE v2 on multiple networks. 

ultimately we are going to have to delete the hardcoded Manifests, and update them in place with a mustache script with these config files

2022-03-29 14:35 UTC, davekaj commented on subgraphs/aave-v2/config/polygon.json
> -    "network": "polygon",
same comment as above

2022-03-29 14:35 UTC, davekaj commented on subgraphs/aave-v3/src/helpers/account.ts
> +export function addToLiquidationCount(accountId: string, isLiquidated: boolean): void {
this function should be passed `account: Account` instead of the `accountID`, because you already have loaded the account prior to calling this function

2022-03-29 14:35 UTC, davekaj commented on subgraphs/aave-v3/src/helpers/account.ts
> +    acm.depositCount = acm.depositCount.plus(new BigInt(1))
These "counts" can all be changed to `Ints`. Reason being is the JS number limit is 2^53 - 1, and so BigInt is not needed. 

deposit, withdraw, etc. can be changed

2022-03-29 14:35 UTC, davekaj commented on subgraphs/aave-v3/src/helpers/generic.ts
> +export const AAVE_V3_REGISTRY = "0x770ef9f4fe897e59daCc474EF11238303F9552b6"
This is not needed. we should be reading off of `event.address` whenever needed. 

reason being - this will not translate when we try to track AAVE v3 on 5-10 different networks. this is the aave-v3 address only for polygon

2022-03-29 18:15 UTC, nmimran99 commented
NOTE: 
Additional work needs to be done on NETWORK specifications

2022-03-29 20:09 UTC, davekay100 approved these changes

2022-03-29 20:35 UTC, merged